### PR TITLE
Metadata Refactor

### PR DESCRIPTION
**Pull request by echavemann**
Open Convo PR right now

### CODE REVIEW

**Comment by echavemann** [comment]
Ready for Merge.

**Comment by echavemann** [comment]
Closes #13

**Comment by echavemann** [comment]
Contributes to #8

**Comment by jiale0402** [comment]
has this been tested?

**Review by jiale0402 — APPROVED** [review]

**Comment by echavemann** [comment]
yes this is fully tested, confirmed working

**Pull request merged**
