### PR TITLE
adjust for feature warm up period

### PR DESCRIPTION
**Pull request by jiale0402**
image

### CODE REVIEW

**Review by echavemann — APPROVED** [review]

**Comment by echavemann** [comment]
@jiale0402 can we merge this?

**Comment by jiale0402** [comment]
> @jiale0402 can we merge this?

actually no, now that I think about it this change also changes the timeframe in authored in metadata, causing mismatch in timeframes of features and raw

**Comment by echavemann** [comment]
what are we doing with this PR

**Comment by echavemann** [comment]
superseded ^

**Pull request closed without merging**
