### PR TITLE
fix paths & add warning for default path

### PR DESCRIPTION
**Pull request by jiale0402**
fixed pathing (solution is not os agnostic) + changed default prompt to path warning
tested on dent, confirmed working for default path case 
截屏2023-09-20 下午12 08 37

### CODE REVIEW

**Comment by echavemann** [comment]
i forgot to fix this oops

**Comment by echavemann** [comment]
yea i said to set it back to what it was

**Comment by echavemann** [comment]
in this comm https://github.com/walkway-project/utils/commit/b4e13489b38b1940b90c8442c9059ab287da5b15

**Comment by echavemann** [comment]
we should be joining catalyst root to Data

**Comment by jiale0402** [comment]
commit 15a9b1e like this?

**Comment by echavemann** [comment]
tested? if so im down to merge (lets squash so we have a good msg)

**Review by echavemann — APPROVED** [review]
i think right, not sure tho

**Comment by jiale0402** [comment]
yea tested this morning

**Pull request merged**
