### PR TITLE
Implementing Dynamic Timeframes

### PR DESCRIPTION
**Pull request by echavemann**

### CODE REVIEW

**Comment by echavemann** [comment]
Closes #3

**Comment by jiale0402** [comment]
not sure where to find the dynamic timeframe implementation?

**Comment by echavemann** [comment]
think i missed a file, updating

**Comment by jiale0402** [comment]
i don't think enum is enough, what if the user specifies a range that's not alr enumerated? what if the range partially overlaps with exisitng data? python has a datetime package for handling date ranges just use it lol

**Comment by echavemann** [comment]
no thats dumb just use the ranges

**Comment by jiale0402** [comment]
what happens if i want data for 2022/1/1 to 2022/2/2 and data for 2022/10/10 to 2022/12/12 to exist together

**Comment by echavemann** [comment]
why dont u just get 2022/1/1 -> 2022/12/12

**Comment by jiale0402** [comment]
because i don't want to spend storage for data that i won't be using?

**Comment by echavemann** [comment]
that defeats the point of a cache/warehouse

**Comment by echavemann** [comment]
u dont get 1s features if ur not holding the superset

**Comment by echavemann** [comment]
fixed lets make sure we squash this

**Pull request merged**
